@verbatim
  <!-- <div class="bg-red-500 p-6 rounded-xl h-[570px]">
      <div class="grid grid-cols-12 bg-white gap-x-2">
        <div class="col-span-2">
          <div class="hover:text-white p-2 rounded border" 
          :class="dateActive ? 'bg-gray-800 hover:bg-gray-700 text-white' : 'bg-gray-800 hover:bg-gray-700 text-gray-400'"
            v-for="(item,i) in dateArr" :key="i" 
            @click="activeDate(i)">
            asasasasasa
          </div>
        </div>
        <div class="col-span-10 bg-gray-600/60">
          <h1>TES2</h1>
        </div>
      </div>
    </div> -->

  <div class="grid grid-cols-12 gap-x-4 space-x-4 gap-y-4 p-6 rounded-xl">
    <div class="col-span-4 grid-rows-2 space-y-4 h-fit">
      <div class=" bg-white bg-opacity-95 border-t-4 border-[#00AA13] py-4 rounded-lg px-3">
        <div class="flex justify-between p-2">
          <!-- <h3 class="text-lg font-semibold">Calendar</h3> -->
          <FieldX :bind="{ readonly: false }" class="!mt-0" :value="values.month"
            :errorText="formErrors.month?'failed':''" @input="v=>{
                values.month=v
                changeCalendar(v)
                }" :hints="formErrors.month" placeholder="Pilih Bulan" label="" type="month" :check="false" />

        </div>
        <table class="border-collapse text-[#757575] mb-4 w-full">
          <tr>
            <th v-for="day in daysOfWeek" :key="day" class="p-1 font-semibold">{{ day }}</th>
          </tr>
          <tr v-for="row in calendarRows" :key="row" class="">
            <td v-for="cell in row" :key="cell.date"
              :class="{ 'bg-[#00AA13] text-white': cell.isToday, 'cursor-pointer':cell.day }" class="p-1 text-center"
              @click="handleDateClick(cell.date)">{{ cell . day }}</td>
          </tr>
        </table>
        <div class="bg-[#00AA13] h-[1px] mb-2"></div>
        <div class="flex justify-between">
          <i class="text-gray-600">Silahkan Pilih Tanggal Diatas</i>
          <icon fa="times" size="lg mr-0.5 cursor-pointer text-red-600" v-show="isDateSucs" @click="resetAll()" />
        </div>


        <!-- Ini label -->
        <div v-show="isDateSucs" class="p-4" style="max-height: 250px; overflow-y: auto;">

          <div class="mb-3">
            <input type="text" v-model="searchQuery" placeholder="Cari label..."
              class="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-500" />
          </div>

          <div class="grid grid-cols-2 gap-x-4 gap-y-2 mt-2 mb-5">

            <button v-for="(item, i) in filteredLabels" :key="i" @click="getDate(item.label)"
              :class="values.label == item.label ? 'ring-4 outline-none ring-green-300' : ''"
              class="w-full bg-green-600 text-white font-semibold hover:bg-green-500 transition-transform duration-300 transform hover:-translate-y-0.5 rounded-md p-2">
              {{ item . label }}
            </button>

          </div>
        </div>


        <div>
          <!-- <button
          v-if="filteredLabels.length > 0"  
          @click="toggleLabel"
          class="bg-red-500 hover:bg-red-700 duration-300 rounded-xl text-white p-2 font-semibold">
          {{ isDateSucs ? 'Buat Label Baru +' : 'Tampilkan Label Lama' }}
        </button> -->

          <FieldSelect v-show="!isDateSucs" class="!mt-4" :bind="{ disabled: false, clearable:false }"
            :value="values.m_group_kary_id" @input="v=>values.m_group_kary_id=v"
            :errorText="formErrors.m_group_kary_id?'failed':''" :hints="formErrors.m_group_kary_id" valueField="id"
            displayField="nama" :api="{
                  url: `${store.server.url_backend}/operation/m_kary_group`,
                  headers: { 'Content-Type': 'Application/json', Authorization: `${store.user.token_type} ${store.user.token}`},
                  params: {
                    simplest:true,
                    transform:true,
                    join:false,
                    pic:true
                  }
              }" @update:valueFull="e=>{
                values.label= e.nama
                values.pic_id = e.pic_id
                getKaryGroup(e.id)
              }" placeholder="Group Karyawan" :check="false" />

          <FieldX :bind="{ readonly: true }" :value="values.label" :errorText="formErrors.label?'failed':''"
            @input="v=>values.label=v" :hints="formErrors.label" placeholder="Label is Generated By System" label="Label"
            :check="false" />



          <FieldPopup :bind="{ readonly: false }" class="!mt-4" :value="values.pic_id" @input="(v)=>values.pic_id=v"
            :errorText="formErrors.pic_id?'failed':''" :hints="formErrors.pic_id" valueField="id"
            displayField="nama_lengkap" :api="{
                url: `${store.server.url_backend}/operation/m_kary`,
                headers: { 'Content-Type': 'Application/json', Authorization: `${store.user.token_type} ${store.user.token}`},
                params: {
                  simplest:true,
                  searchfield: 'this.id,this.kode,m_divisi.nama,this.nama_lengkap'
                }
              }" placeholder="PIC" :check="false" :columns="[{
                checkboxSelection: true,
                headerCheckboxSelection: true,
                headerName: 'No',
                valueGetter:p=>'',
                width:60,
                sortable: false, resizable: true, filter: false,
                cellClass: ['justify-center', 'bg-gray-50', '!border-gray-200']
              },
              {
                flex: 1,
                field: 'kode',
                headerName:  'NIK PIC',
                sortable: false, resizable: true, filter: 'ColFilter',
                cellClass: ['border-r', '!border-gray-200', 'justify-center']
              },
              {
                flex: 1,
                field: 'm_divisi.nama',
                headerName:  'Divisi',
                sortable: false, resizable: true, filter: 'ColFilter',
                cellClass: ['border-r', '!border-gray-200', 'justify-center']
              },
              {
                flex: 1,
                field: 'nama_lengkap',
                headerName:  'Nama PIC',
                sortable: false, resizable: true, filter: 'ColFilter',
                cellClass: ['border-r', '!border-gray-200', 'justify-center']
              },
              ]" />
        </div>

      </div>

      <div class=" bg-white bg-opacity-95 border-t-4 border-gray-600 py-4 rounded-lg px-3">
        <div class="flex justify-between">
          <span>Total Penghasilan</span><span>{{formatCurrency(values . total_pendapatan)}}</span>
        </div>
        <div class="flex justify-between">
          <span>Total Karyawan</span><span>{{values . jml_kary}}</span>
        </div>
        <div class="flex justify-between items-center">
          <span>Pendapatan Per Karyawan</span><span>{{formatCurrency(values . pend_kary)}}</span>
        </div>
      </div>
    </div>
    <div class="col-span-8 h-fit ">
      <div class="grid grid-cols-12 w-full text-sm overflow-x-auto">
        <button
          class="block col-span-2 bg-gray-400/50 hover:bg-gray-200 rounded-t-lg w-full flex items-center justify-center border-b-2 border-gray-400 p-3 hover:border-blue-600 hover:text-blue-600 duration-300"
          :class="{'bg-gray-200 border-blue-600 text-blue-600 font-bold': activeTabIndex === 0}"
          @click="activeTabIndex = 0">
          Tarif
        </button>
        <button
          class="block col-span-2 bg-gray-400/50 hover:bg-gray-200 rounded-t-lg w-full flex items-center justify-center border-b-2 border-gray-400 p-3 hover:border-blue-600 hover:text-blue-600 duration-300"
          :class="{'bg-gray-200 border-blue-600 text-blue-600 font-bold': activeTabIndex === 1}"
          @click="activeTabIndex = 1">
          Karyawan
        </button>
      </div>
      <div class="bg-white p-4 rounded-b-lg rounded-tr-lg" v-show="activeTabIndex == 0">
        <div class="flex justify-between">
          <h1 class="font-semibold text-lg">Detail Tarif</h1>
          <ButtonMultiSelect title="Add to List" @add="onDetailAdd" :api="{
                url: `${store.server.url_backend}/operation/m_tarif`,
                headers: { 'Content-Type': 'Application/json', Authorization: `${store.user.token_type} ${store.user.token}`},
                params: { simplest: true, searchfield: 'this.nama,this.nominal',},
                onsuccess:(response)=>{
                  response.data = [...response.data].map((dt)=>{
                    dt['m_tarif_id'] = dt['id']
                    dt['m_tarif.nama'] = dt['nama']
                    dt['tarif_desc'] = dt['nama']
                    dt['m_tarif_group_id'] = dt['m_tarif_group_id']
                    dt['qty'] = 1
                    dt['tarif'] = dt['nominal'] ?? 0
                    dt['subtotal'] = dt['nominal']*dt['qty'] ?? 0
                    dt['keterangan'] = dt['keterangan']
                    return dt
                  })
                  response.page = response.current_page
                  response.hasNext = response.has_next
                  return response
                }
              }" :columns="[{
                  checkboxSelection: true,
                  headerCheckboxSelection: true,
                  headerName: 'No',
                  valueGetter:p=>'',
                  width:60,
                  sortable: false, resizable: true, filter: false,
                  cellClass: ['justify-center', 'bg-gray-50', '!border-gray-200']
                },
                {
                  flex: 1,
                  headerName : 'Nama',
                  field: 'nama',
                  wrapText:true,
                  sortable: false, resizable: true, filter: 'ColFilter',
                  cellClass: ['border-r', '!border-gray-200', 'justify-start']
                },
                  {
      headerName: 'Nominal',
      field: 'nominal',
      filter: true,
      sortable: true,
      flex:1,
      filter: 'ColFilter',
      resizable: true,
      cellClass: [ 'border-r', '!border-gray-200', 'justify-end'],
      valueFormatter: params => {
      // Format number to Rupiah currency
      return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR' }).format(params.value);
    },
    },
                {
                  flex: 1,
                  headerName : 'Keterangan',
                  field: 'keterangan',
                  wrapText:true,
                  sortable: false, resizable: true, filter: 'ColFilter',
                  cellClass: ['border-r', '!border-gray-200', 'justify-start']
                },
              ]">
            <div
              class="bg-blue-600 text-white font-semibold hover:bg-blue-500 transition-transform duration-300 transform hover:-translate-y-0.5 rounded p-1.5">
              <icon fa="plus" size="sm mr-0.5" /> Add to List
            </div>
          </ButtonMultiSelect>
        </div>

        <TableStatic :key="tableKey" ref="detail" :value="detailArr" @input="onRetotal" :columns="[{
            headerName: 'No',
            cellRenderer: 'ButtonGrid',
            valueGetter:p=>p.node.rowIndex + 1,
            cellRendererParams: {
              showValue: true,
              icon: 'times',
              class: 'btn-text-danger',
              click:(app)=>{
                if (app && app.params) {
                  const row = app.params.node.data
                  swal.fire({
                    icon: 'warning', showDenyButton: true,
                    text: `Hapus Baris ${app.params.node.rowIndex-(-1)}?`,
                  }).then((res) => {
                    if (res.isConfirmed) {
                      app.params.api.applyTransaction({ remove: [app.params.node.data] })
                      removeDetail(app.params.node.data.id)
                    }
                  })
                }
              }
            },
            width: 60,
            sortable: false, resizable: true, filter: false,
            cellClass: ['justify-center', 'bg-gray-50']
          },
          {
            flex: 1,
            headerName: 'Nama Item',
            field: 'm_tarif_id',
            editable: true,
            sortable: false, resizable: true, filter: false,
            cellClass: ['!border-gray-200', 'justify-start'],
            cellEditor: 'FieldSelect',
            valueGetter:(p)=> p.node.data['m_tarif.nama'],
            cellEditorParams: {
              api: {
                url: `${store.server.url_backend}/operation/m_tarif`,
                headers: {
                  'Content-Type': 'Application/json', Authorization: `${store.user.token_type} ${store.user.token}`
                },
                params: { simplest: true,  
                selectfield: 'this.id,this.nama,this.nominal',
          },
              },
              displayField:'nama',
              valueField:'id',
              bind: { clearable:true },
              input(val, api){
                api.data['m_tarif_id']=val.id
                api.data['m_tarif.nama']=val.nama
                api.data['tarif_desc']=val.nama
                api.data['qty'] = 1
                api.data['tarif'] = val['nominal'] ?? 0
                api.data['subtotal'] = val['nominal']*api.data['qty'] ?? 0
                api.data['keterangan'] = val['keterangan'] ?? null
                values.amt=detailArr.map(d=>d.total_amt)
              },
            },
          },
          {
            flex:1,
            headerName: 'Tarif',
            field: 'tarif',
            editable: true,
            sortable: false, resizable: true, filter: false,
            cellClass: ['!border-gray-200', 'justify-end'],
            cellRenderer: (p) => parseFloat(p.value||0).toLocaleString('id'),
            cellEditor: 'FieldNumber',
            cellEditorParams: {
              input(val, api){
                api.data['tarif']=val
                api.data['subtotal']=parseFloat(api.data['tarif']??0)*parseFloat(api.data['qty'])
                values.amt=detailArr.map(d=>d.total_amt)
              }
            }
          },
          {
            flex:1,
            headerName: 'Jumlah Item',
            field: 'qty',
            editable: true,
            sortable: false, resizable: true, filter: false,
            cellClass: ['!border-gray-200', 'justify-end'],
            cellRenderer: (p) => parseFloat(p.value||0).toLocaleString('id'),
            cellEditor: 'FieldNumber',
            cellEditorParams: {
              input(val, api){
                api.data['qty']=val
                api.data['subtotal']=parseFloat(api.data['tarif']??0)*parseFloat(api.data['qty'])
                values.amt=detailArr.map(d=>d.total_amt)
              }
            }
          },
          {
            flex:1,
            headerName: 'Sub Total',
            field: 'subtotal',
            editable: false,
            sortable: false, resizable: true, filter: false,
            cellClass: ['!border-gray-200', 'justify-end'],
            cellRenderer: (p) => parseFloat(p.value||0).toLocaleString('id'),
            cellEditor: 'FieldNumber',
            cellEditorParams: {
              input(val, api){
                api.data['subtotal']=val
                values.amt=detailArr.map(d=>d.total_amt)
              }
            }
          },
          {
    flex: 1,
    headerName: 'Keterangan', // Menambahkan judul kolom
    field: 'keterangan', // Menambahkan field 'keterangan' dari data
    editable: true,
    sortable: false,
    resizable: true,
    filter: false,
    cellClass: ['!border-gray-200', 'justify-start'],
    cellEditor: 'FieldText', // Jenis editor, misalnya untuk teks
    cellEditorParams: {
      input(val, api) {
        api.data['keterangan'] = val; // Memperbarui nilai keterangan
      },
    },
  }
        ]">
          <template #header></template>
        </TableStatic>

        <div class="flex justify-end mt-4">
          <button @click="onSave" class="bg-[#10B981] hover:bg-[#0ea774] text-white px-[36.5px] py-[12px] rounded-[6px] ">
            Simpan
          </button>
        </div>
      </div>


      <div class="bg-white rounded-b-lg rounded-tr-lg p-4" v-show="activeTabIndex == 1">
        <div class="flex justify-between">
          <h1 class="font-semibold text-lg">Detail Karyawan</h1>
          <ButtonMultiSelect title="Add to List" @add="onDetailAddKary" :api="{
                url: `${store.server.url_backend}/operation/m_kary`,
                headers: { 'Content-Type': 'Application/json', Authorization: `${store.user.token_type} ${store.user.token}`},
                params: {
                  simplest:true,
                  searchfield: 'this.id,this.kode,m_divisi.nama,this.nama_lengkap',
                }, 
                onsuccess:(response)=>{
                  response.data = [...response.data].map((dt)=>{
                    // Object.keys(dt).forEach(k=>dt['m_item.'+k] = dt[k])
                    dt['m_kary_id'] = dt['id']
                    dt['m_dept.nama'] = dt['m_dept.nama']
                    return dt
                  })
                  response.page = response.current_page
                  response.hasNext = response.has_next
                  return response
                }
              }" placeholder="Karyawan" :check="false" :columns="[{
                headerName: 'No',
                valueGetter:(p)=>p.node.rowIndex + 1,
                width: 60,
                sortable: false, resizable: false, filter: false,
                cellClass: ['justify-center', 'bg-gray-50']
              },
              {
                flex: 1,
                field: 'kode',
                headerName:  'NIK Karyawan',
                sortable: false, resizable: true, filter: 'ColFilter',
                cellClass: ['border-r', '!border-gray-200', 'justify-center']
              },
              {
                flex: 1,
                field: 'm_divisi.nama',
                headerName:  'Divisi',
                sortable: false, resizable: true, filter: 'ColFilter',
                cellClass: ['border-r', '!border-gray-200', 'justify-center']
              },
              {
                flex: 1,
                field: 'nama_lengkap',
                headerName:  'Nama Karyawan',
                sortable: false, resizable: true, filter: 'ColFilter',
                cellClass: ['border-r', '!border-gray-200', 'justify-center']
              },
              ]">
            <div
              class="bg-blue-600 text-white font-semibold hover:bg-blue-500 transition-transform duration-300 transform hover:-translate-y-0.5 rounded p-1.5">
              <icon fa="plus" size="sm mr-0.5" /> Add to List
            </div>
          </ButtonMultiSelect>

        </div>
        <TableStatic :key="tableKeyKary" ref="detailKary" :value="detailArrKary" @input="onRetotal" :columns="[{
                headerName: 'No',
                cellRenderer: 'ButtonGrid',
                valueGetter:p=>p.node.rowIndex + 1,
                cellRendererParams: {
                  showValue: true,
                  icon: 'times',
                  class: 'btn-text-danger',
                  click:(app)=>{
                    if (app && app.params) {
                      const row = app.params.node.data
                      swal.fire({
                        icon: 'warning', showDenyButton: true,
                        text: `Hapus Baris ${app.params.node.rowIndex-(-1)}?`,
                      }).then((res) => {
                        if (res.isConfirmed) {
                          app.params.api.applyTransaction({ remove: [app.params.node.data] })
                          removeDetailKary(app.params.node.data.id)
                        }
                      })
                    }
                  }
                },
                width: 60,
                sortable: false, resizable: true, filter: false,
                cellClass: ['justify-center', 'bg-gray-50']
              },
              {
                flex: 1,
                headerName: 'Nama Departemen',
                field: 'm_dept_id',
                editable: true,
                sortable: false, resizable: true, filter: false,
                cellClass: ['!border-gray-200', 'justify-start'],
                cellEditor: 'FieldSelect',
                valueGetter:(p)=> p.node.data['m_dept.nama'],
                cellEditor: 'FieldSelect',
                cellEditorParams: {
                  api: {
                    url: `${store.server.url_backend}/operation/m_dept`,
                    headers: {
                      'Content-Type': 'Application/json', Authorization: `${store.user.token_type} ${store.user.token}`
                    },
                    params: { simplest: true,   },
                  },
                  displayField:'nama',
                  valueField:'id',
                  bind: { clearable:true },
                  input(val, api){
                    api.data['m_dept_id']=val.id
                    api.data['m_dept.nama']=val.code
                    values.amt=detailArr.map(d=>d.total_amt)
                  },
                },
              },
              {
                flex:1,
                headerName: 'Nama Karyawan',
                field: 'nama_lengkap',
                editable: true,
                sortable: false, resizable: true, filter: false,
                cellClass: ['!border-gray-200', 'justify-start'],
                cellEditor: 'FieldX',
                cellEditorParams: {
                  input(val, api){
                    api.data['tarif']=val
                    values.amt=detailArr.map(d=>d.total_amt)
                  }
                }
              },
              {
                flex:1,
                headerName: 'NIK',
                field: 'kode',
                editable: true,
                sortable: false, resizable: true, filter: false,
                cellClass: ['!border-gray-200', 'justify-end'],
                cellEditor: 'FieldX',
                cellEditorParams: {
                  input(val, api){
                    api.data['kode']=val
                    values.amt=detailArr.map(d=>d.total_amt)
                  }
                }
              },
              ]">
          <template #header></template>
        </TableStatic>
        <div class="flex justify-end mt-4">
          <button @click="onSave" class="bg-[#10B981] hover:bg-[#0ea774] text-white px-[36.5px] py-[12px] rounded-[6px] ">
            Simpan
          </button>
        </div>
      </div>

    </div>
  </div>

@endverbatim